import type { Metadata } from 'next'
import './global.css'
import Header from './components/Header'
import { paragraph } from './fonts'
import { AuthProvider } from './context/AuthContext'

export const metadata: Metadata = {

  title: 'Touiter, the new Twitter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body style={paragraph.style}>
      <AuthProvider>
      <Header />
      {children}
      </AuthProvider>
      </body>
      
    </html>
  )
}
