import type { Metadata } from 'next'
import './global.css'
import Header from './components/Header'
import { adamina } from './fonts'
export const metadata: Metadata = {
  title: 'Touiter, the new Twitter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={adamina.style}>
      <Header />
      {children}</body>
    </html>
  )
}
